name: firma_blockchain_app
description: "App de firma digital con blockchain"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 FIREBASE (OBLIGATORIO)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # 📂 ARCHIVOS
  file_picker: ^6.1.1

  # 🔐 CRIPTOGRAFÍA (para hash después)
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true