// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFWWIrXOwXVSzPRQg4qAg5AmVk7jBomu0',
    appId: '1:55851784405:web:6e89c7d1444e5ea0946a5c',
    messagingSenderId: '55851784405',
    projectId: 'firma-blockchain-app',
    authDomain: 'firma-blockchain-app.firebaseapp.com',
    storageBucket: 'firma-blockchain-app.firebasestorage.app',
    measurementId: 'G-8L63CZELCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9VBU29JNTU2Fg8ohHWpduEQjZ2WP4exk',
    appId: '1:55851784405:android:dd8521c77135bd31946a5c',
    messagingSenderId: '55851784405',
    projectId: 'firma-blockchain-app',
    storageBucket: 'firma-blockchain-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmWc6gtektXOvjSI4oEsBpqCDUYy_Aisc',
    appId: '1:55851784405:ios:f8721dc167bd7544946a5c',
    messagingSenderId: '55851784405',
    projectId: 'firma-blockchain-app',
    storageBucket: 'firma-blockchain-app.firebasestorage.app',
    iosBundleId: 'com.example.firmaBlockchainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmWc6gtektXOvjSI4oEsBpqCDUYy_Aisc',
    appId: '1:55851784405:ios:f8721dc167bd7544946a5c',
    messagingSenderId: '55851784405',
    projectId: 'firma-blockchain-app',
    storageBucket: 'firma-blockchain-app.firebasestorage.app',
    iosBundleId: 'com.example.firmaBlockchainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFWWIrXOwXVSzPRQg4qAg5AmVk7jBomu0',
    appId: '1:55851784405:web:c6b5c82712bfd438946a5c',
    messagingSenderId: '55851784405',
    projectId: 'firma-blockchain-app',
    authDomain: 'firma-blockchain-app.firebaseapp.com',
    storageBucket: 'firma-blockchain-app.firebasestorage.app',
    measurementId: 'G-K1GHRCB6XZ',
  );

}